var searchData=
[
  ['aabbpositionskhr_0',['AabbPositionsKHR',['../struct_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_aabb_positions_k_h_r.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['accelerationstructurebuildgeometryinfokhr_1',['AccelerationStructureBuildGeometryInfoKHR',['../struct_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_acceleration_structure_build_geometry_info_k_h_r.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['accelerationstructurebuildrangeinfokhr_2',['AccelerationStructureBuildRangeInfoKHR',['../struct_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_acceleration_structure_build_range_info_k_h_r.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['accelerationstructurebuildsizesinfokhr_3',['AccelerationStructureBuildSizesInfoKHR',['../struct_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_acceleration_structure_build_sizes_info_k_h_r.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['accelerationstructurecreateinfokhr_4',['AccelerationStructureCreateInfoKHR',['../struct_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_acceleration_structure_create_info_k_h_r.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['accelerationstructurecreateinfonv_5',['AccelerationStructureCreateInfoNV',['../struct_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_acceleration_structure_create_info_n_v.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['accelerationstructuredeviceaddressinfokhr_6',['AccelerationStructureDeviceAddressInfoKHR',['../struct_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_acceleration_structure_device_address_info_k_h_r.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['accelerationstructuregeometryaabbsdatakhr_7',['AccelerationStructureGeometryAabbsDataKHR',['../struct_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_acceleration_structure_geometry_aabbs_data_k_h_r.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['accelerationstructuregeometrydatakhr_8',['AccelerationStructureGeometryDataKHR',['../union_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_acceleration_structure_geometry_data_k_h_r.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['accelerationstructuregeometryinstancesdatakhr_9',['AccelerationStructureGeometryInstancesDataKHR',['../struct_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_acceleration_structure_geometry_instances_data_k_h_r.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['accelerationstructuregeometrykhr_10',['AccelerationStructureGeometryKHR',['../struct_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_acceleration_structure_geometry_k_h_r.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['accelerationstructuregeometrytrianglesdatakhr_11',['AccelerationStructureGeometryTrianglesDataKHR',['../struct_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_acceleration_structure_geometry_triangles_data_k_h_r.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['accelerationstructureinfonv_12',['AccelerationStructureInfoNV',['../struct_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_acceleration_structure_info_n_v.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['accelerationstructureinstancekhr_13',['AccelerationStructureInstanceKHR',['../struct_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_acceleration_structure_instance_k_h_r.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['accelerationstructurekhr_14',['AccelerationStructureKHR',['../class_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_acceleration_structure_k_h_r.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['accelerationstructurememoryrequirementsinfonv_15',['AccelerationStructureMemoryRequirementsInfoNV',['../struct_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_acceleration_structure_memory_requirements_info_n_v.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['accelerationstructurenv_16',['AccelerationStructureNV',['../class_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_acceleration_structure_n_v.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['accelerationstructureversioninfokhr_17',['AccelerationStructureVersionInfoKHR',['../struct_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_acceleration_structure_version_info_k_h_r.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['acquirenextimageinfokhr_18',['AcquireNextImageInfoKHR',['../struct_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_acquire_next_image_info_k_h_r.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['acquireprofilinglockinfokhr_19',['AcquireProfilingLockInfoKHR',['../struct_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_acquire_profiling_lock_info_k_h_r.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['adevice_20',['adevice',['../union_s_d_l___event.html#a111e01fcac4fd8e251a6058ff9f17e72',1,'SDL_Event']]],
  ['allocation_20names_20and_20user_20data_21',['Allocation names and user data',['../allocation_annotation.html',1,'index']]],
  ['allocationbytes_22',['allocationBytes',['../struct_vma_budget.html#a7e2a6583ebd63e194951c542563804d8',1,'VmaBudget']]],
  ['allocationcallbacks_23',['AllocationCallbacks',['../struct_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_allocation_callbacks.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['allocationcount_24',['allocationCount',['../struct_vma_defragmentation_info2.html#a3cf86ab32c1da779b4923d301a3056ba',1,'VmaDefragmentationInfo2::allocationCount()'],['../struct_vma_pool_stats.html#ad1924eb54fffa45e9e0e65670c8fe5eb',1,'VmaPoolStats::allocationCount()'],['../struct_vma_stat_info.html#a537741e4d5cdddc1c0ab95ec650afaff',1,'VmaStatInfo::allocationCount()']]],
  ['allocationsmoved_25',['allocationsMoved',['../struct_vma_defragmentation_stats.html#aefeabf130022008eadd75999478af3f9',1,'VmaDefragmentationStats']]],
  ['app_26',['app',['../class_l_graphics_1_1_l_widget.html#afb1a6f0c4d6f17b768d2fb5d5c400e51',1,'LGraphics::LWidget']]],
  ['applicationinfo_27',['ApplicationInfo',['../struct_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_application_info.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['arrayproxy_28',['ArrayProxy',['../class_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_array_proxy.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['arrayproxynotemporaries_29',['ArrayProxyNoTemporaries',['../class_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_array_proxy_no_temporaries.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['arraywrapper1d_30',['ArrayWrapper1D',['../class_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_array_wrapper1_d.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['arraywrapper1d_3c_20char_2c_20vk_5fmax_5fdescription_5fsize_20_3e_31',['ArrayWrapper1D&lt; char, VK_MAX_DESCRIPTION_SIZE &gt;',['../class_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_array_wrapper1_d.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['arraywrapper1d_3c_20char_2c_20vk_5fmax_5fdriver_5finfo_5fsize_20_3e_32',['ArrayWrapper1D&lt; char, VK_MAX_DRIVER_INFO_SIZE &gt;',['../class_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_array_wrapper1_d.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['arraywrapper1d_3c_20char_2c_20vk_5fmax_5fdriver_5fname_5fsize_20_3e_33',['ArrayWrapper1D&lt; char, VK_MAX_DRIVER_NAME_SIZE &gt;',['../class_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_array_wrapper1_d.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['arraywrapper1d_3c_20char_2c_20vk_5fmax_5fextension_5fname_5fsize_20_3e_34',['ArrayWrapper1D&lt; char, VK_MAX_EXTENSION_NAME_SIZE &gt;',['../class_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_array_wrapper1_d.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['arraywrapper1d_3c_20char_2c_20vk_5fmax_5fphysical_5fdevice_5fname_5fsize_20_3e_35',['ArrayWrapper1D&lt; char, VK_MAX_PHYSICAL_DEVICE_NAME_SIZE &gt;',['../class_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_array_wrapper1_d.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['arraywrapper1d_3c_20float_2c_202_20_3e_36',['ArrayWrapper1D&lt; float, 2 &gt;',['../class_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_array_wrapper1_d.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['arraywrapper1d_3c_20float_2c_204_20_3e_37',['ArrayWrapper1D&lt; float, 4 &gt;',['../class_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_array_wrapper1_d.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['arraywrapper1d_3c_20int32_5ft_2c_204_20_3e_38',['ArrayWrapper1D&lt; int32_t, 4 &gt;',['../class_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_array_wrapper1_d.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['arraywrapper1d_3c_20uint32_5ft_2c_202_20_3e_39',['ArrayWrapper1D&lt; uint32_t, 2 &gt;',['../class_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_array_wrapper1_d.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['arraywrapper1d_3c_20uint32_5ft_2c_203_20_3e_40',['ArrayWrapper1D&lt; uint32_t, 3 &gt;',['../class_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_array_wrapper1_d.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['arraywrapper1d_3c_20uint32_5ft_2c_204_20_3e_41',['ArrayWrapper1D&lt; uint32_t, 4 &gt;',['../class_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_array_wrapper1_d.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['arraywrapper1d_3c_20uint32_5ft_2c_20vk_5fmax_5fdevice_5fgroup_5fsize_20_3e_42',['ArrayWrapper1D&lt; uint32_t, VK_MAX_DEVICE_GROUP_SIZE &gt;',['../class_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_array_wrapper1_d.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['arraywrapper1d_3c_20uint8_5ft_2c_20vk_5fluid_5fsize_20_3e_43',['ArrayWrapper1D&lt; uint8_t, VK_LUID_SIZE &gt;',['../class_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_array_wrapper1_d.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['arraywrapper1d_3c_20uint8_5ft_2c_20vk_5fuuid_5fsize_20_3e_44',['ArrayWrapper1D&lt; uint8_t, VK_UUID_SIZE &gt;',['../class_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_array_wrapper1_d.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['arraywrapper1d_3c_20vulkan_5fhpp_5fnamespace_3a_3adevicesize_2c_20vk_5fmax_5fmemory_5fheaps_20_3e_45',['ArrayWrapper1D&lt; VULKAN_HPP_NAMESPACE::DeviceSize, VK_MAX_MEMORY_HEAPS &gt;',['../class_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_array_wrapper1_d.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['arraywrapper1d_3c_20vulkan_5fhpp_5fnamespace_3a_3afragmentshadingratecombineropkhr_2c_202_20_3e_46',['ArrayWrapper1D&lt; VULKAN_HPP_NAMESPACE::FragmentShadingRateCombinerOpKHR, 2 &gt;',['../class_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_array_wrapper1_d.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['arraywrapper1d_3c_20vulkan_5fhpp_5fnamespace_3a_3amemoryheap_2c_20vk_5fmax_5fmemory_5fheaps_20_3e_47',['ArrayWrapper1D&lt; VULKAN_HPP_NAMESPACE::MemoryHeap, VK_MAX_MEMORY_HEAPS &gt;',['../class_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_array_wrapper1_d.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['arraywrapper1d_3c_20vulkan_5fhpp_5fnamespace_3a_3amemorytype_2c_20vk_5fmax_5fmemory_5ftypes_20_3e_48',['ArrayWrapper1D&lt; VULKAN_HPP_NAMESPACE::MemoryType, VK_MAX_MEMORY_TYPES &gt;',['../class_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_array_wrapper1_d.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['arraywrapper1d_3c_20vulkan_5fhpp_5fnamespace_3a_3aoffset3d_2c_202_20_3e_49',['ArrayWrapper1D&lt; VULKAN_HPP_NAMESPACE::Offset3D, 2 &gt;',['../class_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_array_wrapper1_d.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['arraywrapper1d_3c_20vulkan_5fhpp_5fnamespace_3a_3aphysicaldevice_2c_20vk_5fmax_5fdevice_5fgroup_5fsize_20_3e_50',['ArrayWrapper1D&lt; VULKAN_HPP_NAMESPACE::PhysicalDevice, VK_MAX_DEVICE_GROUP_SIZE &gt;',['../class_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_array_wrapper1_d.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['arraywrapper2d_51',['ArrayWrapper2D',['../class_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_array_wrapper2_d.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['arraywrapper2d_3c_20float_2c_203_2c_204_20_3e_52',['ArrayWrapper2D&lt; float, 3, 4 &gt;',['../class_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_array_wrapper2_d.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['assert_5ffail_53',['ASSERT_FAIL',['../_s_d_l__test__assert_8h.html#adc9dbc949d8699a6f6515211a2efa0cf',1,'SDL_test_assert.h']]],
  ['assert_5fpass_54',['ASSERT_PASS',['../_s_d_l__test__assert_8h.html#ae67a2f28e6df1e351df870754835a09a',1,'SDL_test_assert.h']]],
  ['attachmentdescription_55',['AttachmentDescription',['../struct_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_attachment_description.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['attachmentdescription2_56',['AttachmentDescription2',['../struct_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_attachment_description2.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['attachmentdescriptionstencillayout_57',['AttachmentDescriptionStencilLayout',['../struct_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_attachment_description_stencil_layout.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['attachmentreference_58',['AttachmentReference',['../struct_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_attachment_reference.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['attachmentreference2_59',['AttachmentReference2',['../struct_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_attachment_reference2.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['attachmentreferencestencillayout_60',['AttachmentReferenceStencilLayout',['../struct_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_attachment_reference_stencil_layout.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['attachmentsamplelocationsext_61',['AttachmentSampleLocationsEXT',['../struct_v_u_l_k_a_n___h_p_p___n_a_m_e_s_p_a_c_e_1_1_attachment_sample_locations_e_x_t.html',1,'VULKAN_HPP_NAMESPACE']]],
  ['attack_5flength_62',['attack_length',['../struct_s_d_l___haptic_custom.html#a018b35d89398c26e10d1fb4315d1dda1',1,'SDL_HapticCustom::attack_length()'],['../struct_s_d_l___haptic_constant.html#a907bade68ab53fb24e7d2651d19b767f',1,'SDL_HapticConstant::attack_length()'],['../struct_s_d_l___haptic_periodic.html#ab35eedce7107edc75640586159fe75bb',1,'SDL_HapticPeriodic::attack_length()'],['../struct_s_d_l___haptic_ramp.html#adbcd7ffb05016d442c73e81cc0fcbbd2',1,'SDL_HapticRamp::attack_length()']]],
  ['attack_5flevel_63',['attack_level',['../struct_s_d_l___haptic_custom.html#ad6e394e3775372af3eb9e02823987405',1,'SDL_HapticCustom::attack_level()'],['../struct_s_d_l___haptic_constant.html#a0928a37f3fab0e5b7daffc7a1d65744c',1,'SDL_HapticConstant::attack_level()'],['../struct_s_d_l___haptic_periodic.html#a79fc2217fea6db6ab3d89ad905d52ccb',1,'SDL_HapticPeriodic::attack_level()'],['../struct_s_d_l___haptic_ramp.html#a755933bbda14ae9b53c574b9fe6291a0',1,'SDL_HapticRamp::attack_level()']]],
  ['audio_5ff32lsb_64',['AUDIO_F32LSB',['../_s_d_l__audio_8h.html#afaef57ecb718053b572c539e27e72d61',1,'SDL_audio.h']]],
  ['audio_5ff32msb_65',['AUDIO_F32MSB',['../_s_d_l__audio_8h.html#a2d57382c01fdcd78cbbbb480605d91ef',1,'SDL_audio.h']]],
  ['audio_5fs16lsb_66',['AUDIO_S16LSB',['../_s_d_l__audio_8h.html#a23838d612e88ce72d82c3e51460f831b',1,'SDL_audio.h']]],
  ['audio_5fs16msb_67',['AUDIO_S16MSB',['../_s_d_l__audio_8h.html#a3109dfb1d7aab29dff2b62d630e690ca',1,'SDL_audio.h']]],
  ['audio_5fs32lsb_68',['AUDIO_S32LSB',['../_s_d_l__audio_8h.html#ac81f9cc5739cea67436daf2689d29559',1,'SDL_audio.h']]],
  ['audio_5fs32msb_69',['AUDIO_S32MSB',['../_s_d_l__audio_8h.html#a30641d7487680630c231b3415ecd47b6',1,'SDL_audio.h']]],
  ['audio_5fs8_70',['AUDIO_S8',['../_s_d_l__audio_8h.html#a883b3d4539451e49bf014dde0f9cca29',1,'SDL_audio.h']]],
  ['audio_5fu16lsb_71',['AUDIO_U16LSB',['../_s_d_l__audio_8h.html#a06808f806896c4d211314990c354b7fc',1,'SDL_audio.h']]],
  ['audio_5fu16msb_72',['AUDIO_U16MSB',['../_s_d_l__audio_8h.html#a3b8052d0c49d14a2e3edf08eade52d3a',1,'SDL_audio.h']]],
  ['audio_5fu8_73',['AUDIO_U8',['../_s_d_l__audio_8h.html#a6468b4b3fc53ada655eca866e491d75f',1,'SDL_audio.h']]],
  ['axes_74',['axes',['../struct_g_l_f_wgamepadstate.html#a8b2c8939b1d31458de5359998375c189',1,'GLFWgamepadstate']]],
  ['axis_75',['axis',['../struct_s_d_l___controller_axis_event.html#aba6543c143521aebce06a41a8cf79db0',1,'SDL_ControllerAxisEvent::axis()'],['../struct_s_d_l___joy_axis_event.html#a0beac2fb161e45771c424bd0b6daeabb',1,'SDL_JoyAxisEvent::axis()']]]
];
